apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: .
    repoURL: oci://public.ecr.aws/karpenter/karpenter
    targetRevision: 1.6.0
    helm:
      parameters:
        - name: settings.clusterName
          value: {{ .Values.clusterName }}
        - name: serviceAccount.annotations.eks\.amazonaws\.com/role-arn
          value: "arn:aws:iam::485928541354:role/sd-dev-feaver-01"
        - name: controller.resources.requests.cpu
          value: "1"
        - name: controller.resources.requests.memory
          value: "1Gi"
        - name: controller.resources.limits.cpu
          value: "1"
        - name: controller.resources.limits.memory
          value: "1Gi"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: karpenter
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
