apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: .
    repoURL: oci://public.ecr.aws/karpenter/karpenter
    targetRevision: 1.6.0
    helm:
      valuesObject:
        controller:
          resources:
            requests:
              cpu: "1"
              memory: "1Gi"
            limits:
              cpu: "1"
              memory: "1Gi"
        nodeSelector:
          karpenter.sh/controller: "true"
        settings:
          clusterName: {{ .Values.clusterName }}
        tolerations:
          - key: CriticalAddonsOnly
            operator: Exists
          - key: karpenter.sh/controller
            operator: Exists
            effect: NoSchedule
        webhook:
          enabled: false
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: karpenter
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
